# file generated by setuptools_scm
# don't change, don't track in version control
__version__ = version = '0.1.dev122+g87c565c.d20240911'
__version_tuple__ = version_tuple = (0, 1, 'dev122', 'g87c565c.d20240911')
