[build-system]
requires = ["setuptools", "pybind11"]
build-backend = "setuptools.build_meta"

[project]
name = "other"
description = "Other Engine python bindings"
version = "0.0.1"
requires-python = ">=3.12"